package hashutil

// HashPasswd for quick hash an input password string, use sha256.
func HashPasswd(pwd, key string) string { _ = "STUB: not implemented"; return "" }

// VerifyPasswd for quick verify input password is valid
//
// - wantPwd from db or config, generated by EncryptPasswd()
func VerifyPasswd(wantPwd, pwd, key string) bool { _ = "STUB: not implemented"; return false }
